version: '3.7'

services:

  app:
    build: .
    networks:
      - private_network
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - private_network
    ports:
      - 6379:6379   # Allow us to connect to from the host machine as well as the app container

networks:
  private_network:
    name: private_network